baseURL = 'https://cybersnow.io/'
languageCode = 'en-us'
title = 'CYBERSNOW // DOCUMENTATION'
theme = 'terminal'

[params]
  themeColor = "blue" 
  showMenuItems = 2
  fullPostContent = true
  customCSS = ["style.css"]