baseURL = 'https://cybersnow.io/'
languageCode = 'en-us'
title = 'CYBERSNOW // DOCUMENTATION'
theme = 'terminal'

[params]
  # This sets a custom neon cyan color instead of the boring presets
  themeColor = "#00ffff"
  showMenuItems = 2
  fullPostContent = true